export const ADD_ARTICLE = "ADD_ARTICLE"
export const UPDATE_ARTICLE = "UPDATE_ARTICLE"
export const DELETE_ARTICLE = "DELETE_ARTICLE"

export const DELETE_ARTICLE_COLLECTION = "DELETE_ARTICLE_COLLECTION"